Repository postmanlabs/postman-collection-transformer, pull requests merged in 2018-07, with the labels that each got.

#105 Fixed regex for protocol extraction (URL parsing)
  lib/url.js
  test/unit/url.test.js
Labels: bug

#106 Updated dependencies :arrow_up:
  package.json
Labels: greenkeeper

#107 Empty description handling
  lib/converters/v1.0.0/converter-v1-to-v2.js
  lib/converters/v2.0.0/converter-v2-to-v1.js
  lib/converters/v2.1.0/converter-v21-to-v1.js
  lib/normalizers/v1.js
  lib/util.js
  test/unit/v1.0.0/converter-v1-to-v2.test.js
  test/unit/v1.0.0/converter-v1-to-v21.test.js
  test/unit/v1.0.0/normalize-v1.test.js
  test/unit/v2.0.0/converter-v2-to-v1.test.js
  test/unit/v2.1.0/converter-v21-to-v1.test.js
Labels: bug

#108 Lint improvements
  .eslintrc
  bin/transform-collection.js
  lib/common/v1.js
  lib/common/v2.js
  lib/constants.js
  lib/converters/index.js
  lib/converters/v1.0.0/converter-v1-to-v2.js
  lib/converters/v1.0.0/converter-v1-to-v21.js
  lib/converters/v2.0.0/converter-v2-to-v1.js
  lib/converters/v2.1.0/converter-v21-to-v1.js
  lib/index.js
  lib/normalizers/index.js
  lib/normalizers/v1.js
  lib/url.js
  lib/util.js
  npm/.eslintrc
  npm/test-browser.js
  npm/test-lint.js
  npm/test-schema.js
  npm/test-system.js
  npm/test-unit.js
  test/.eslintrc
  test/schema/example-validity.test.js
  test/schema/v1.0.0/converter-v1-to-v2.test.js
  test/schema/v1.0.0/converter-v1-to-v21.test.js
  test/schema/v2.0.0/converter-v2-to-v1.test.js
  test/schema/v2.1.0/converter-v21-to-v1.test.js
  test/system/repository.test.js
  test/system/travis-yml.test.js
  test/unit/fixtures/sample-collection.js
  test/unit/v1.0.0/converter-v1-to-v2.test.js
  test/unit/v1.0.0/converter-v1-to-v21.test.js
  test/unit/v1.0.0/normalize-v1.test.js
  test/unit/v2.0.0/converter-v2-to-v1.test.js
  test/unit/v2.1.0/converter-v21-to-v1.test.js
Labels: enhancement

#109 More tests
  lib/converters/v1.0.0/converter-v1-to-v21.js
  lib/converters/v2.0.0/converter-v2-to-v1.js
  lib/converters/v2.1.0/converter-v21-to-v1.js
  lib/index.js
  npm/test-unit.js
  test/unit/converter.test.js
  test/unit/lib.test.js
  test/unit/url.test.js
  test/unit/util.test.js
  test/unit/v1.0.0/converter-v1-to-v2.test.js
  test/unit/v1.0.0/converter-v1-to-v21.test.js
  test/unit/v1.0.0/normalize-v1.test.js
  test/unit/v2.0.0/converter-v2-to-v1.test.js
  test/unit/v2.1.0/converter-v21-to-v1.test.js
Labels: tests

#110 Do not regenerate folder ids when for v2.x to v1 (ignore `retainIds`)
  lib/converters/v2.0.0/converter-v2-to-v1.js
  test/unit/fixtures/multi-level.v2.json
  test/unit/fixtures/multi-level.v21.json
  test/unit/v2.0.0/converter-v2-to-v1.test.js
  test/unit/v2.1.0/converter-v21-to-v1.test.js
Labels: bug
