Repository postmanlabs/postman-collection-transformer, pull requests merged in 2019-05, with the labels that each got.

#209 Greenkeeper/strip json comments 3.0.1
  package-lock.json
  package.json
Labels: greenkeeper

#210 Greenkeeper/nyc 14.1.1
  npm/test-unit.js
  package-lock.json
  package.json
Labels: greenkeeper

#207 Added support for GraphQL request body
  .gitignore
  .npmignore
  docs/request-body.md
  lib/common/v2.js
  lib/converters/v1.0.0/converter-v1-to-v2.js
  lib/converters/v2.0.0/converter-v2-to-v1.js
  test/unit/v1.0.0/converter-v1-to-v2.test.js
  test/unit/v1.0.0/converter-v1-to-v21.test.js
  test/unit/v2.0.0/converter-v2-to-v1.test.js
  test/unit/v2.1.0/converter-v21-to-v1.test.js
Labels: enhancement

#214 Greenkeeper/eslint plugin jsdoc 5.0.2
  package-lock.json
  package.json
Labels: greenkeeper

#213 Fixed a bug where params with empty key get filtered
  CHANGELOG.yaml
  lib/converters/v1.0.0/converter-v1-to-v2.js
  test/unit/v1.0.0/converter-v1-to-v2.test.js
Labels: bug
